name: Test Workflow with Allure
on: 
  push:
  workflow_dispatch:
      inputs:
        ALLURE_JOB_RUN_ID:
          description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
          required: false
        ALLURE_USERNAME:
          description: "ALLURE_USERNAME service parameter. Leave blank"
          required: false
jobs:
  allure-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Allure installation
        uses: allure-framework/setup-allurectl@v1
        with: 
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
      - run: allurectl watch -- npm run test
        env:
          ALLURE_TESTPLAN_PATH: "./testplan.json"
          ALLURE_RESULTS: ./allure-results
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
