name: Test Workflow with Allure
on: workflow_dispatch
jobs:
  allure-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Allure installation
        uses: allure-framework/setup-allurectl@v1
        with: 
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
      - run: ./allurectl watch -- npm run test
        env: 
          ALLURE_RESULTS: ./allure-results
