name: Test Workflow with Allure
on: workflow_dispatch
env:
  ALLURE_TESTPLAN_PATH: "./testplan.json"
  ALLURE_RESULTS: ./allure-results
jobs:
  allure-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Allure installation
        uses: allure-framework/setup-allurectl@v1
        with: 
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
      - run: allurectl job-run plan --output-file ${ALLURE_TESTPLAN_PATH}
      - run: allurectl watch -- npm run test
